etcd:
  image: quay.io/coreos/etcd:v3.0.10
  command: ['/usr/local/bin/etcd', '-advertise-client-urls=http://etcd:2379', '-listen-client-urls=http://0.0.0.0:2379', '--data-dir=/var/etcd/data']

apiserver:
  image: gcr.io/google_containers/hyperkube:v1.3.7
  privileged: true
  command: ["/hyperkube", "apiserver", "--service-cluster-ip-range=172.17.17.1/24", "--insecure-bind-address=0.0.0.0", "--etcd_servers=http://etcd:2379", "--v=2"]
  ports:
    - 8080:8080
  links:
    - etcd

controller:
  image: gcr.io/google_containers/hyperkube:v1.3.7
  command: ["/hyperkube", "controller-manager", "--master=http://apiserver:8080", "--v=2"]
  links:
    - apiserver

scheduler:
  image: gcr.io/google_containers/hyperkube:v1.3.7
  command: ["/hyperkube", "scheduler", "--master=http://apiserver:8080", "--v=2"]
  links:
    - apiserver

kubelet:
  image: gcr.io/google_containers/hyperkube:v1.3.7
  pid: host
  privileged: true
  command: ['/hyperkube', 'kubelet', '--api_servers=http://apiserver:8080', '--v=2', '--address=0.0.0.0', '--enable_server', '--cluster-dns=10.254.0.10', '--cluster-domain=cluster.local']
  volumes:
    - /var/lib/kubelet/:/var/lib/kubelet:rw
    - /var/lib/docker/:/var/lib/docker:ro
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/run/docker.pid:/var/run/docker.pid:ro
    - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
  links:
    - apiserver

proxy:
  image: gcr.io/google_containers/hyperkube:v1.4.0
  pid: host
  privileged: true
  command: ['/hyperkube', 'proxy', '--master=http://apiserver:8080', '--v=2', '--conntrack-max=0', '--conntrack-max-per-core=0', '--conntrack-tcp-timeout-established=0']
  privileged: true
  volumes:
    - /sys:/sys
    - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
  links:
    - apiserver

kube2sky:
  image: gcr.io/google_containers/kube2sky:1.15
  command: ['--kube-master-url=http://apiserver:8080', '--domain=cluster.local', '--etcd-server=http://etcd:2379']
  links:
    - apiserver
    - etcd

skydns:
  image: skynetservices/skydns:2.5.3a
  command: ['--machines=http://etcd:2379', '--addr=0.0.0.0:53', '--domain=cluster.local', '-ns-rotate=false']
  links:
    - etcd

dashboard:
  image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.4.0
  command: ['--apiserver-host=http://apiserver:8080']
  ports:
    - 9090:9090
  links:
    - apiserver
