apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: devpi
spec:
  ports:
  - port: 3141
    protocol: TCP
    targetPort: 3141
  selector:
    run: devpi
status:
  loadBalancer: {}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: devpi
  name: devpi
spec:
  replicas: 1
  selector:
    matchLabels:
      run: devpi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: devpi
    spec:
      containers:
      - image: muccg/devpi
        name: devpi
        ports:
        - containerPort: 3141
        resources: {}
status: {}
